
# Site
title: 屈定's Blog
subtitle: 屈定's Blog
subtitle_desc: 编程是一件幸福的事情,不要让工作变得索然无味
keywords: IT小生, Java, Spring, Mybatis, 后端工程师,
description: 日常学习与兴趣交流的个人博客
introduction: 不思量，自难忘！
favicon_ico: https://avatars1.githubusercontent.com/u/13889883?v=3&s=460
logo: http://oobu4m7ko.bkt.clouddn.com/newlogo.png
qrcode: http://oobu4m7ko.bkt.clouddn.com/1514796045.png?imageMogr2/thumbnail/!50p
default_cover: http://oobu4m7ko.bkt.clouddn.com/1514801425.png
header_cover: http://oobu4m7ko.bkt.clouddn.com/21312.jpg
error_page_bg: http://oobu4m7ko.bkt.clouddn.com/21312.jpg
author:
  name: 屈定
  link: https://github.com/mrdear
about:
  info: 本站定位为个人博客,主要记录自己成为程序员以来的成长历程.
  address: ShangHai, China
  email: niudear@foxmail.com

# Menu
menu:
  home: /
  archive: /archives
  about: /about

highlight_theme: normal

loader_img: http://oo12ugek5.bkt.clouddn.com/blog/images/loader.gif
